#!/bin/bash
go run main.go &&
chmod 0777 ./app &&
cd ./app &&
docker-compose up -d --build &&
docker-compose ps &&
pwd &&
cp ../node_modules_23.tar ../app/front/node_modules.tar &&
 cd front &&
 tar -xvf node_modules.tar &&
cd ../ &&

# Перевірка статусу контейнера MySQL
until docker exec app-mysql-1 mysqladmin ping -uroot -proot --silent; do
    echo "Waiting for MySQL service to respond..."
    sleep 5
done

docker exec -i app-mysql-1 mysql -uroot -proot < sql.sql &&
cd back &&
go get -d -v ./... && go install -v ./... && go build -o server .
echo "&& (./server &) && cd ../front && (npm start &)"
